name: Reuse

on: [workflow_dispatch]

jobs:
 call-workflow:
   uses: ./.github/workflows/reusable.yml
   with: 
     who-to-great: R.

 use-output:
   runs-on: ubuntu-latest
   needs: [call-workflow]
   steps:
     - name: echo
       run: echo "Time ${{ needs.call-workflow.outputs.current-time }}"
     
